services:
  - type: web
    name: couponvault-demo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gthread --threads 10 --workers 1 app:app"

